import { Inter } from "next/font/google";
import * as Tooltip from "@radix-ui/react-tooltip";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Character Studio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <Tooltip.Provider
          delayDuration={150}
          skipDelayDuration={300}
          disableHoverableContent
        >
          {children}
        </Tooltip.Provider>
      </body>
    </html>
  );
}
